//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSPE.Service.CamManager.Test.FbFWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fulcrumbiometrics.com/", ConfigurationName="FbFWebService.StandardServiceSoap")]
    public interface StandardServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/EnrollBiometric", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricResponse EnrollBiometric(SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/EnrollBiometric", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricResponse> EnrollBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/EnrollImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.EnrollImageResponse EnrollImage(SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/EnrollImage", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.EnrollImageResponse> EnrollImageAsync(SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/DeleteBiometric", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricResponse DeleteBiometric(SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/DeleteBiometric", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricResponse> DeleteBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/IdentifyBiometric", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricResponse IdentifyBiometric(SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/IdentifyBiometric", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricResponse> IdentifyBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/IdentifyImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageResponse IdentifyImage(SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/IdentifyImage", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageResponse> IdentifyImageAsync(SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GeneralizeTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateResponse GeneralizeTemplate(SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GeneralizeTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateResponse> GeneralizeTemplateAsync(SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest request);
        
        // CODEGEN: Parameter 'ExtractTemplateResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/ExtractTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse ExtractTemplate(SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/ExtractTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse> ExtractTemplateAsync(SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GetServerCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetServerCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GetServerCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetServerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GetServerConfiguration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SSPE.Service.CamManager.Test.FbFWebService.FbFConfig GetServerConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fulcrumbiometrics.com/GetServerConfiguration", ReplyAction="*")]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.FbFConfig> GetServerConfigurationAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFBioTemplate[] templatesField;
        
        private int recordidField;
        
        private string personidField;
        
        private string taxonomyField;
        
        private FbFBioLocations locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("biotemplate")]
        public FbFBioTemplate[] templates {
            get {
                return this.templatesField;
            }
            set {
                this.templatesField = value;
                this.RaisePropertyChanged("templates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int recordid {
            get {
                return this.recordidField;
            }
            set {
                this.recordidField = value;
                this.RaisePropertyChanged("recordid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string personid {
            get {
                return this.personidField;
            }
            set {
                this.personidField = value;
                this.RaisePropertyChanged("personid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string taxonomy {
            get {
                return this.taxonomyField;
            }
            set {
                this.taxonomyField = value;
                this.RaisePropertyChanged("taxonomy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFBioLocations location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFBioTemplate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string templateField;
        
        private FbFTemplateTypes typeField;
        
        private FbFBioAttributes gField;
        
        private int qualityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("template");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFTemplateTypes type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFBioAttributes G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
                this.RaisePropertyChanged("G");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
                this.RaisePropertyChanged("quality");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFTemplateTypes {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        MMStandard = 2,
        
        /// <remarks/>
        MMLite = 4,
        
        /// <remarks/>
        ISO = 8,
        
        /// <remarks/>
        ANSI = 16,
        
        /// <remarks/>
        NIST = 32,
        
        /// <remarks/>
        IdKit = 64,
        
        /// <remarks/>
        FujitsuStandard = 128,
        
        /// <remarks/>
        TopazStandard = 256,
        
        /// <remarks/>
        IrisIdLong = 512,
        
        /// <remarks/>
        IrisIdShort = 1024,
        
        /// <remarks/>
        FujitsuStandardV2 = 2048,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFBioAttributes {
        
        /// <remarks/>
        G = 1,
        
        /// <remarks/>
        Quality = 2,
        
        /// <remarks/>
        NFIQ = 4,
        
        /// <remarks/>
        MinutiaMap = 8,
        
        /// <remarks/>
        VectorMap = 16,
        
        /// <remarks/>
        Segementation = 32,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int majorField;
        
        private int minorField;
        
        private int buildField;
        
        private int revisionField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
                this.RaisePropertyChanged("minor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
                this.RaisePropertyChanged("build");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFLicense : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFLicenseTypes nameField;
        
        private int countField;
        
        private string userfriendlynameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFLicenseTypes name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userfriendlyname {
            get {
                return this.userfriendlynameField;
            }
            set {
                this.userfriendlynameField = value;
                this.RaisePropertyChanged("userfriendlyname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFLicenseTypes {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        Client = 2,
        
        /// <remarks/>
        Server = 4,
        
        /// <remarks/>
        Device_Finger = 8,
        
        /// <remarks/>
        Device_Camera = 16,
        
        /// <remarks/>
        Device_Iris = 32,
        
        /// <remarks/>
        Device_Palm = 64,
        
        /// <remarks/>
        Biometrics_Standard_Fingers = 128,
        
        /// <remarks/>
        Biometrics_Tools_NFIQ = 256,
        
        /// <remarks/>
        Client_LiveScan_MultiFinger = 512,
        
        /// <remarks/>
        Biometrics_FingerMatching = 1024,
        
        /// <remarks/>
        Biometrics_FingerExtraction = 2048,
        
        /// <remarks/>
        Biometrics_FaceMatching = 4096,
        
        /// <remarks/>
        Biometrics_FaceExtraction = 8192,
        
        /// <remarks/>
        Biometrics_IrisMatching = 16384,
        
        /// <remarks/>
        Biometrics_Standard_Faces = 32768,
        
        /// <remarks/>
        Biometrics_Standard_Irises = 65536,
        
        /// <remarks/>
        Biometrics_IrisExtraction = 131072,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFLicenseConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFLicense[] licensesField;
        
        private string[] acquiredlicensesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("license")]
        public FbFLicense[] licenses {
            get {
                return this.licensesField;
            }
            set {
                this.licensesField = value;
                this.RaisePropertyChanged("licenses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("license")]
        public string[] acquiredlicenses {
            get {
                return this.acquiredlicensesField;
            }
            set {
                this.acquiredlicensesField = value;
                this.RaisePropertyChanged("acquiredlicenses");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFLicenseConfig licenseconfigurationField;
        
        private FbFVersion versionconfigurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FbFLicenseConfig licenseconfiguration {
            get {
                return this.licenseconfigurationField;
            }
            set {
                this.licenseconfigurationField = value;
                this.RaisePropertyChanged("licenseconfiguration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FbFVersion versionconfiguration {
            get {
                return this.versionconfigurationField;
            }
            set {
                this.versionconfigurationField = value;
                this.RaisePropertyChanged("versionconfiguration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFException innerexceptionField;
        
        private long errorcodeField;
        
        private string errormessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FbFException innerexception {
            get {
                return this.innerexceptionField;
            }
            set {
                this.innerexceptionField = value;
                this.RaisePropertyChanged("innerexception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
                this.RaisePropertyChanged("errorcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                this.errormessageField = value;
                this.RaisePropertyChanged("errormessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFBioImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] rawbitmapField;
        
        private byte[] rawwsqField;
        
        private string imageField;
        
        private FbFImageTypes typeField;
        
        private bool persistField;
        
        private string nfiqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] rawbitmap {
            get {
                return this.rawbitmapField;
            }
            set {
                this.rawbitmapField = value;
                this.RaisePropertyChanged("rawbitmap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] rawwsq {
            get {
                return this.rawwsqField;
            }
            set {
                this.rawwsqField = value;
                this.RaisePropertyChanged("rawwsq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFImageTypes type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool persist {
            get {
                return this.persistField;
            }
            set {
                this.persistField = value;
                this.RaisePropertyChanged("persist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nfiq {
            get {
                return this.nfiqField;
            }
            set {
                this.nfiqField = value;
                this.RaisePropertyChanged("nfiq");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFImageTypes {
        
        /// <remarks/>
        RawBitmap = 1,
        
        /// <remarks/>
        RawWSQ = 2,
        
        /// <remarks/>
        BinarizedJPG = 4,
        
        /// <remarks/>
        BinarizedPNG = 8,
        
        /// <remarks/>
        BinarizedBMP = 16,
        
        /// <remarks/>
        BinarizedWSQ = 32,
        
        /// <remarks/>
        RefreshJPG = 64,
        
        /// <remarks/>
        RefreshPNG = 128,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public partial class FbFBioResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FbFBioTemplate[] templatesField;
        
        private FbFBioImage[] imagesField;
        
        private string recordidField;
        
        private FbFResultStatuses statusField;
        
        private FbFBioLocations biolocationField;
        
        private int matchscoreField;
        
        private int matchidField;
        
        private string personidField;
        
        private int generalizedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("biotemplates")]
        public FbFBioTemplate[] templates {
            get {
                return this.templatesField;
            }
            set {
                this.templatesField = value;
                this.RaisePropertyChanged("templates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bioimages")]
        public FbFBioImage[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
                this.RaisePropertyChanged("images");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string recordid {
            get {
                return this.recordidField;
            }
            set {
                this.recordidField = value;
                this.RaisePropertyChanged("recordid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFResultStatuses status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FbFBioLocations biolocation {
            get {
                return this.biolocationField;
            }
            set {
                this.biolocationField = value;
                this.RaisePropertyChanged("biolocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int matchscore {
            get {
                return this.matchscoreField;
            }
            set {
                this.matchscoreField = value;
                this.RaisePropertyChanged("matchscore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int matchid {
            get {
                return this.matchidField;
            }
            set {
                this.matchidField = value;
                this.RaisePropertyChanged("matchid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string personid {
            get {
                return this.personidField;
            }
            set {
                this.personidField = value;
                this.RaisePropertyChanged("personid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int generalized {
            get {
                return this.generalizedField;
            }
            set {
                this.generalizedField = value;
                this.RaisePropertyChanged("generalized");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFResultStatuses {
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        Identified,
        
        /// <remarks/>
        Generalized,
        
        /// <remarks/>
        FusedIdentified,
        
        /// <remarks/>
        Verified,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Added,
        
        /// <remarks/>
        Removed,
        
        /// <remarks/>
        Captured,
        
        /// <remarks/>
        CaptureStarted,
        
        /// <remarks/>
        CaptureStopped,
        
        /// <remarks/>
        DeviceEnumerationFailed,
        
        /// <remarks/>
        LicenseError,
        
        /// <remarks/>
        ExtractionFailed,
        
        /// <remarks/>
        DeviceUnplugged,
        
        /// <remarks/>
        DevicePluggedIn,
        
        /// <remarks/>
        DeviceNotAvailable,
        
        /// <remarks/>
        StartScanningFailed,
        
        /// <remarks/>
        AlreadySubscribed,
        
        /// <remarks/>
        ConfigRequestFailed,
        
        /// <remarks/>
        SubscriptionPaused,
        
        /// <remarks/>
        SubscriptionResumed,
        
        /// <remarks/>
        PamlVeinMessageNoGuidance,
        
        /// <remarks/>
        PamlVeinMessageStopMoving,
        
        /// <remarks/>
        PamlVeinMessageCorrectly,
        
        /// <remarks/>
        PamlVeinMessageClose,
        
        /// <remarks/>
        PamlVeinMessageKeepAway,
        
        /// <remarks/>
        PamlVeinMessageSaving,
        
        /// <remarks/>
        PamlVeinMessageAuthenticating,
        
        /// <remarks/>
        PamlVeinMessageMoveAway,
        
        /// <remarks/>
        PamlVeinMessageMoveLeft,
        
        /// <remarks/>
        PamlVeinMessageMoveRight,
        
        /// <remarks/>
        PamlVeinMessageMoveForward,
        
        /// <remarks/>
        PamlVeinMessageMoveBackward,
        
        /// <remarks/>
        PamlVeinMessageEvenUp,
        
        /// <remarks/>
        PamlVeinMessageSensorOrient,
        
        /// <remarks/>
        PamlVeinMessageFingerOpen,
        
        /// <remarks/>
        PamlVeinMessageBrightMoment,
        
        /// <remarks/>
        PamlVeinMessageBrightNg,
        
        /// <remarks/>
        PamlVeinMessageHoldUpHand,
        
        /// <remarks/>
        PamlVeinMessageFlattenOut,
        
        /// <remarks/>
        Segemented,
        
        /// <remarks/>
        DeviceNotSupported,
        
        /// <remarks/>
        Missing,
        
        /// <remarks/>
        DeviceTiltUpsideDown,
        
        /// <remarks/>
        DeviceTiltNormal,
        
        /// <remarks/>
        TransactionTimeOut,
        
        /// <remarks/>
        DeviceDriverError,
        
        /// <remarks/>
        TemplateFormatError,
        
        /// <remarks/>
        Updated,
        
        /// <remarks/>
        GeneralizedAndIdentified,
        
        /// <remarks/>
        GeneralizedAndNotIdentified,
        
        /// <remarks/>
        TemplateMismatch,
        
        /// <remarks/>
        LowTemplateQuality,
        
        /// <remarks/>
        UnsupportedBiolocation,
        
        /// <remarks/>
        ReceivingImage,
        
        /// <remarks/>
        FailedToOpenComPort,
        
        /// <remarks/>
        AcquiringLicense,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFBioLocations {
        
        /// <remarks/>
        UnknownFinger,
        
        /// <remarks/>
        RightThumb,
        
        /// <remarks/>
        RightIndex,
        
        /// <remarks/>
        RightMiddle,
        
        /// <remarks/>
        RightRing,
        
        /// <remarks/>
        RightLittle,
        
        /// <remarks/>
        LeftThumb,
        
        /// <remarks/>
        LeftIndex,
        
        /// <remarks/>
        LeftMiddle,
        
        /// <remarks/>
        LeftRing,
        
        /// <remarks/>
        LeftLittle,
        
        /// <remarks/>
        LeftExtra,
        
        /// <remarks/>
        RightExtra,
        
        /// <remarks/>
        UnknownTwoFinger,
        
        /// <remarks/>
        LeftIndexMiddle,
        
        /// <remarks/>
        LeftRingLittle,
        
        /// <remarks/>
        Thumbs,
        
        /// <remarks/>
        RightIndexMiddle,
        
        /// <remarks/>
        RightRingLittle,
        
        /// <remarks/>
        TwoFingersExtra,
        
        /// <remarks/>
        UnknownFourFinger,
        
        /// <remarks/>
        LeftFourFinger,
        
        /// <remarks/>
        RightFourFinger,
        
        /// <remarks/>
        UnknownPalm,
        
        /// <remarks/>
        LeftPalm,
        
        /// <remarks/>
        RightPalm,
        
        /// <remarks/>
        UnknownFace,
        
        /// <remarks/>
        FaceFront,
        
        /// <remarks/>
        FaceLeft45,
        
        /// <remarks/>
        FaceLeft90,
        
        /// <remarks/>
        FaceRight45,
        
        /// <remarks/>
        FaceRight90,
        
        /// <remarks/>
        UnknownIris,
        
        /// <remarks/>
        LeftIris,
        
        /// <remarks/>
        RightIris,
        
        /// <remarks/>
        BothIris,
        
        /// <remarks/>
        UnknownPalmVeinEnroll,
        
        /// <remarks/>
        UnknownPalmVeinCapture,
        
        /// <remarks/>
        LeftPalmVeinEnroll,
        
        /// <remarks/>
        LeftPalmVeinCapture,
        
        /// <remarks/>
        RightPalmVeinEnroll,
        
        /// <remarks/>
        RightPalmVeinCapture,
        
        /// <remarks/>
        UnknownFingerRolled,
        
        /// <remarks/>
        LeftIndexRolled,
        
        /// <remarks/>
        LeftMiddleRolled,
        
        /// <remarks/>
        LeftRingRolled,
        
        /// <remarks/>
        LeftLittleRolled,
        
        /// <remarks/>
        LeftThumbRolled,
        
        /// <remarks/>
        RightIndexRolled,
        
        /// <remarks/>
        RightMiddleRolled,
        
        /// <remarks/>
        RightRingRolled,
        
        /// <remarks/>
        RightLittleRolled,
        
        /// <remarks/>
        RightThumbRolled,
        
        /// <remarks/>
        LeftExtraRolled,
        
        /// <remarks/>
        RightExtraRolled,
        
        /// <remarks/>
        HandSignature,
        
        /// <remarks/>
        FBIUnknownThumb,
        
        /// <remarks/>
        FBILeftThumb,
        
        /// <remarks/>
        FBIRightThumb,
        
        /// <remarks/>
        FBIUnknownFourFinger,
        
        /// <remarks/>
        FBILeftFourFinger,
        
        /// <remarks/>
        FBIRightFourFinger,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollBiometric", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class EnrollBiometricRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records;
        
        public EnrollBiometricRequest() {
        }
        
        public EnrollBiometricRequest(SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records) {
            this.records = records;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollBiometricResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class EnrollBiometricResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] EnrollBiometricResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFException exception;
        
        public EnrollBiometricResponse() {
        }
        
        public EnrollBiometricResponse(SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] EnrollBiometricResult, SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            this.EnrollBiometricResult = EnrollBiometricResult;
            this.exception = exception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollImage", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class EnrollImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imagedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public string personid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=2)]
        public int biolocation;
        
        public EnrollImageRequest() {
        }
        
        public EnrollImageRequest(byte[] imagedata, string personid, int biolocation) {
            this.imagedata = imagedata;
            this.personid = personid;
            this.biolocation = biolocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollImageResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class EnrollImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public bool EnrollImageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public long exception;
        
        public EnrollImageResponse() {
        }
        
        public EnrollImageResponse(bool EnrollImageResult, long exception) {
            this.EnrollImageResult = EnrollImageResult;
            this.exception = exception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteBiometric", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class DeleteBiometricRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public int biolocation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public string personid;
        
        public DeleteBiometricRequest() {
        }
        
        public DeleteBiometricRequest(int biolocation, string personid) {
            this.biolocation = biolocation;
            this.personid = personid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteBiometricResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class DeleteBiometricResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public bool DeleteBiometricResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFException exception;
        
        public DeleteBiometricResponse() {
        }
        
        public DeleteBiometricResponse(bool DeleteBiometricResult, SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            this.DeleteBiometricResult = DeleteBiometricResult;
            this.exception = exception;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fulcrumbiometrics.com/")]
    public enum FbFResponseStatuses {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Refresh,
        
        /// <remarks/>
        Generalized,
        
        /// <remarks/>
        Extracted,
        
        /// <remarks/>
        Capabilities,
        
        /// <remarks/>
        Acknowledgement,
        
        /// <remarks/>
        ResultsPending,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        DeviceAdded,
        
        /// <remarks/>
        DeviceRemoved,
        
        /// <remarks/>
        Configuration,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifyBiometric", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class IdentifyBiometricRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records;
        
        public IdentifyBiometricRequest() {
        }
        
        public IdentifyBiometricRequest(SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records) {
            this.records = records;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifyBiometricResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class IdentifyBiometricResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] IdentifyBiometricResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFResponseStatuses responsestatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=2)]
        public SSPE.Service.CamManager.Test.FbFWebService.FbFException exception;
        
        public IdentifyBiometricResponse() {
        }
        
        public IdentifyBiometricResponse(SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] IdentifyBiometricResult, SSPE.Service.CamManager.Test.FbFWebService.FbFResponseStatuses responsestatus, SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            this.IdentifyBiometricResult = IdentifyBiometricResult;
            this.responsestatus = responsestatus;
            this.exception = exception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifyImage", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class IdentifyImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imagedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public int biolocation;
        
        public IdentifyImageRequest() {
        }
        
        public IdentifyImageRequest(byte[] imagedata, int biolocation) {
            this.imagedata = imagedata;
            this.biolocation = biolocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IdentifyImageResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class IdentifyImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public string IdentifyImageResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public long exception;
        
        public IdentifyImageResponse() {
        }
        
        public IdentifyImageResponse(string IdentifyImageResult, long exception) {
            this.IdentifyImageResult = IdentifyImageResult;
            this.exception = exception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneralizeTemplate", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class GeneralizeTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        public byte[][] templates;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public int biolocation;
        
        public GeneralizeTemplateRequest() {
        }
        
        public GeneralizeTemplateRequest(byte[][] templates, int biolocation) {
            this.templates = templates;
            this.biolocation = biolocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GeneralizeTemplateResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class GeneralizeTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GeneralizeTemplateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public int responsestatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=2)]
        public long exception;
        
        public GeneralizeTemplateResponse() {
        }
        
        public GeneralizeTemplateResponse(byte[] GeneralizeTemplateResult, int responsestatus, long exception) {
            this.GeneralizeTemplateResult = GeneralizeTemplateResult;
            this.responsestatus = responsestatus;
            this.exception = exception;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTemplate", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class ExtractTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imagedata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=1)]
        public int biolocation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=2)]
        public int templatetype;
        
        public ExtractTemplateRequest() {
        }
        
        public ExtractTemplateRequest(byte[] imagedata, int biolocation, int templatetype) {
            this.imagedata = imagedata;
            this.biolocation = biolocation;
            this.templatetype = templatetype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtractTemplateResponse", WrapperNamespace="http://fulcrumbiometrics.com/", IsWrapped=true)]
    public partial class ExtractTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fulcrumbiometrics.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ExtractTemplateResult;
        
        public ExtractTemplateResponse() {
        }
        
        public ExtractTemplateResponse(byte[] ExtractTemplateResult) {
            this.ExtractTemplateResult = ExtractTemplateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StandardServiceSoapChannel : SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StandardServiceSoapClient : System.ServiceModel.ClientBase<SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap>, SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap {
        
        public StandardServiceSoapClient() {
        }
        
        public StandardServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StandardServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StandardServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StandardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.EnrollBiometric(SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest request) {
            return base.Channel.EnrollBiometric(request);
        }
        
        public SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] EnrollBiometric(SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records, out SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest();
            inValue.records = records;
            SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).EnrollBiometric(inValue);
            exception = retVal.exception;
            return retVal.EnrollBiometricResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricResponse> EnrollBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.EnrollBiometricRequest request) {
            return base.Channel.EnrollBiometricAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.EnrollImageResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.EnrollImage(SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest request) {
            return base.Channel.EnrollImage(request);
        }
        
        public bool EnrollImage(byte[] imagedata, string personid, int biolocation, out long exception) {
            SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest();
            inValue.imagedata = imagedata;
            inValue.personid = personid;
            inValue.biolocation = biolocation;
            SSPE.Service.CamManager.Test.FbFWebService.EnrollImageResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).EnrollImage(inValue);
            exception = retVal.exception;
            return retVal.EnrollImageResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.EnrollImageResponse> EnrollImageAsync(SSPE.Service.CamManager.Test.FbFWebService.EnrollImageRequest request) {
            return base.Channel.EnrollImageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.DeleteBiometric(SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest request) {
            return base.Channel.DeleteBiometric(request);
        }
        
        public bool DeleteBiometric(int biolocation, string personid, out SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest();
            inValue.biolocation = biolocation;
            inValue.personid = personid;
            SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).DeleteBiometric(inValue);
            exception = retVal.exception;
            return retVal.DeleteBiometricResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricResponse> DeleteBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.DeleteBiometricRequest request) {
            return base.Channel.DeleteBiometricAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.IdentifyBiometric(SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest request) {
            return base.Channel.IdentifyBiometric(request);
        }
        
        public SSPE.Service.CamManager.Test.FbFWebService.FbFBioResult[] IdentifyBiometric(SSPE.Service.CamManager.Test.FbFWebService.FbFRecord[] records, out SSPE.Service.CamManager.Test.FbFWebService.FbFResponseStatuses responsestatus, out SSPE.Service.CamManager.Test.FbFWebService.FbFException exception) {
            SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest();
            inValue.records = records;
            SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).IdentifyBiometric(inValue);
            responsestatus = retVal.responsestatus;
            exception = retVal.exception;
            return retVal.IdentifyBiometricResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricResponse> IdentifyBiometricAsync(SSPE.Service.CamManager.Test.FbFWebService.IdentifyBiometricRequest request) {
            return base.Channel.IdentifyBiometricAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.IdentifyImage(SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest request) {
            return base.Channel.IdentifyImage(request);
        }
        
        public string IdentifyImage(byte[] imagedata, int biolocation, out long exception) {
            SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest();
            inValue.imagedata = imagedata;
            inValue.biolocation = biolocation;
            SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).IdentifyImage(inValue);
            exception = retVal.exception;
            return retVal.IdentifyImageResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageResponse> IdentifyImageAsync(SSPE.Service.CamManager.Test.FbFWebService.IdentifyImageRequest request) {
            return base.Channel.IdentifyImageAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.GeneralizeTemplate(SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest request) {
            return base.Channel.GeneralizeTemplate(request);
        }
        
        public byte[] GeneralizeTemplate(byte[][] templates, int biolocation, out int responsestatus, out long exception) {
            SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest();
            inValue.templates = templates;
            inValue.biolocation = biolocation;
            SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).GeneralizeTemplate(inValue);
            responsestatus = retVal.responsestatus;
            exception = retVal.exception;
            return retVal.GeneralizeTemplateResult;
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateResponse> GeneralizeTemplateAsync(SSPE.Service.CamManager.Test.FbFWebService.GeneralizeTemplateRequest request) {
            return base.Channel.GeneralizeTemplateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.ExtractTemplate(SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest request) {
            return base.Channel.ExtractTemplate(request);
        }
        
        public byte[] ExtractTemplate(byte[] imagedata, int biolocation, int templatetype) {
            SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest();
            inValue.imagedata = imagedata;
            inValue.biolocation = biolocation;
            inValue.templatetype = templatetype;
            SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse retVal = ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).ExtractTemplate(inValue);
            return retVal.ExtractTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse> SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap.ExtractTemplateAsync(SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest request) {
            return base.Channel.ExtractTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateResponse> ExtractTemplateAsync(byte[] imagedata, int biolocation, int templatetype) {
            SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest inValue = new SSPE.Service.CamManager.Test.FbFWebService.ExtractTemplateRequest();
            inValue.imagedata = imagedata;
            inValue.biolocation = biolocation;
            inValue.templatetype = templatetype;
            return ((SSPE.Service.CamManager.Test.FbFWebService.StandardServiceSoap)(this)).ExtractTemplateAsync(inValue);
        }
        
        public int GetServerCount() {
            return base.Channel.GetServerCount();
        }
        
        public System.Threading.Tasks.Task<int> GetServerCountAsync() {
            return base.Channel.GetServerCountAsync();
        }
        
        public SSPE.Service.CamManager.Test.FbFWebService.FbFConfig GetServerConfiguration() {
            return base.Channel.GetServerConfiguration();
        }
        
        public System.Threading.Tasks.Task<SSPE.Service.CamManager.Test.FbFWebService.FbFConfig> GetServerConfigurationAsync() {
            return base.Channel.GetServerConfigurationAsync();
        }
    }
}
