//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELDA
    {
        public CELDA()
        {
            this.PL_ASIGNACION_RESULTADO = new HashSet<PL_ASIGNACION_RESULTADO>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public short ID_SECTOR { get; set; }
        public string ID_CELDA { get; set; }
        public string ID_TIPO_SEGURIDAD { get; set; }
        public string ID_TIPO_CELDA { get; set; }
        public Nullable<short> NIVEL_EDIFICIO { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PL_ASIGNACION_RESULTADO> PL_ASIGNACION_RESULTADO { get; set; }
        public virtual SECTOR SECTOR { get; set; }
        public virtual TIPO_CELDA TIPO_CELDA { get; set; }
    }
}
