//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRO
    {
        public CENTRO()
        {
            this.EDIFICIOs = new HashSet<EDIFICIO>();
            this.EMPLEADOes = new HashSet<EMPLEADO>();
            this.IMPUTADOes = new HashSet<IMPUTADO>();
            this.INGRESOes = new HashSet<INGRESO>();
            this.PL_PROGRAMADO = new HashSet<PL_PROGRAMADO>();
            this.INGRESOes1 = new HashSet<INGRESO>();
            this.PROCESO_USUARIO = new HashSet<PROCESO_USUARIO>();
            this.USUARIO_ROL = new HashSet<USUARIO_ROL>();
        }
    
        public short ID_CENTRO { get; set; }
        public Nullable<short> ID_TIPO_CENTRO { get; set; }
        public Nullable<short> ID_ENTIDAD { get; set; }
        public Nullable<short> ID_MUNICIPIO { get; set; }
        public string DESCR { get; set; }
        public string CALLE { get; set; }
        public Nullable<int> NUM_EXT { get; set; }
        public string NUM_INT { get; set; }
        public string COLONIA { get; set; }
        public Nullable<int> CP { get; set; }
        public Nullable<long> TELEFONO { get; set; }
        public Nullable<long> FAX { get; set; }
        public string DIRECTOR { get; set; }
        public Nullable<int> ID_EMISOR { get; set; }
        public Nullable<int> CONS_ANUAL { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual TIPO_CENTRO TIPO_CENTRO { get; set; }
        public virtual ICollection<EDIFICIO> EDIFICIOs { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
        public virtual ICollection<IMPUTADO> IMPUTADOes { get; set; }
        public virtual ICollection<INGRESO> INGRESOes { get; set; }
        public virtual ICollection<PL_PROGRAMADO> PL_PROGRAMADO { get; set; }
        public virtual ICollection<INGRESO> INGRESOes1 { get; set; }
        public virtual ICollection<PROCESO_USUARIO> PROCESO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_ROL> USUARIO_ROL { get; set; }
    }
}
