//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.PL_ASIGNACION_BITACORA = new HashSet<PL_ASIGNACION_BITACORA>();
            this.PL_PROGRAMADO_ASIGNACION = new HashSet<PL_PROGRAMADO_ASIGNACION>();
            this.PL_PROGRAMADO = new HashSet<PL_PROGRAMADO>();
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public Nullable<short> ID_TIPO_EMPLEADO { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public string NUMERO_EMPLEADO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> REGISTRO_FEC { get; set; }
        public string OBSERV { get; set; }
        public string CEDULA { get; set; }
        public Nullable<short> ID_DEPARTAMENTO { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual ICollection<PL_ASIGNACION_BITACORA> PL_ASIGNACION_BITACORA { get; set; }
        public virtual ICollection<PL_PROGRAMADO_ASIGNACION> PL_PROGRAMADO_ASIGNACION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        public virtual ICollection<PL_PROGRAMADO> PL_PROGRAMADO { get; set; }
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
