//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO_VISITA
    {
        public short ID { get; set; }
        public Nullable<short> ID_TIPO_VISITA { get; set; }
        public Nullable<short> ID_DIA { get; set; }
        public string HORA_INICIO { get; set; }
        public string HORA_FIN { get; set; }
    
        public virtual TIPO_VISITA TIPO_VISITA { get; set; }
        public virtual VISITA_DIA VISITA_DIA { get; set; }
    }
}
