//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGFALLASERVICIO
    {
        public decimal ID { get; set; }
        public string CODIGODEERROR { get; set; }
        public string MENSAJEDEERROR { get; set; }
        public string DETALLEDELERROR { get; set; }
        public string APPLICATIONNAME { get; set; }
        public Nullable<System.DateTime> FECHADECREACION { get; set; }
    }
}
