//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_ASIGNACION_RESULTADO
    {
        public int ID_ASIGNACION_RESULTADO { get; set; }
        public int ID_PL_ASIGNACION { get; set; }
        public string ID_CELDA { get; set; }
        public Nullable<System.DateTime> HORA_INICIAL { get; set; }
        public Nullable<System.DateTime> HORA_FINAL { get; set; }
        public Nullable<short> ASISTENCIAS { get; set; }
        public Nullable<short> INASISTENCIAS { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public short ID_SECTOR { get; set; }
        public int ID_PL_BITACORA { get; set; }
    
        public virtual CELDA CELDA { get; set; }
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual PL_PROGRAMADO_ASIGNACION PL_PROGRAMADO_ASIGNACION { get; set; }
        public virtual PL_PROGRAMADO_BITACORA PL_PROGRAMADO_BITACORA { get; set; }
        public virtual SECTOR SECTOR { get; set; }
    }
}
