//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_ASIGNACION_BITACORA
    {
        public int ID_ASIGNACION_BITACORA { get; set; }
        public int ID_PL_PROGRAMADO_BITACORA { get; set; }
        public Nullable<System.DateTime> HORA_INICIAL { get; set; }
        public Nullable<System.DateTime> HORA_FINAL { get; set; }
        public int ID_EMPLEADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PL_PROGRAMADO_BITACORA PL_PROGRAMADO_BITACORA { get; set; }
    }
}
