//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_CATALOGO
    {
        public PL_CATALOGO()
        {
            this.PL_PROGRAMADO = new HashSet<PL_PROGRAMADO>();
        }
    
        public short ID_PL_CATALOGO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCR { get; set; }
        public Nullable<System.DateTime> HORA_INICIO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_CREADO { get; set; }
    
        public virtual PL_CATALOGO_ESTATUS PL_CATALOGO_ESTATUS { get; set; }
        public virtual ICollection<PL_PROGRAMADO> PL_PROGRAMADO { get; set; }
    }
}
