//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_CATALOGO_ESTATUS
    {
        public PL_CATALOGO_ESTATUS()
        {
            this.PL_CATALOGO = new HashSet<PL_CATALOGO>();
        }
    
        public string ID_ESTATUS { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<PL_CATALOGO> PL_CATALOGO { get; set; }
    }
}
