//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_INCIDENCIA_BITACORA
    {
        public int ID_PL_INCIDENCIA_BIT { get; set; }
        public Nullable<int> ID_PL_PROGRAMADO_BIT { get; set; }
        public short ID_INCIDENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> HORA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_SOLUCION { get; set; }
        public Nullable<System.DateTime> HORA_SOLUCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTATUS { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_ANIO { get; set; }
        public int ID_IMPUTADO { get; set; }
    
        public virtual IMPUTADO IMPUTADO { get; set; }
        public virtual PL_INCIDENCIA_ESTATUS PL_INCIDENCIA_ESTATUS { get; set; }
        public virtual PL_INCIDENCIA_CATALOGO PL_INCIDENCIA_CATALOGO { get; set; }
        public virtual PL_PROGRAMADO_BITACORA PL_PROGRAMADO_BITACORA { get; set; }
    }
}
