//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_INCIDENCIA_CATALOGO
    {
        public PL_INCIDENCIA_CATALOGO()
        {
            this.PL_INCIDENCIA_BITACORA = new HashSet<PL_INCIDENCIA_BITACORA>();
        }
    
        public short ID { get; set; }
        public string DESCR { get; set; }
        public string LOGIN_MODIF { get; set; }
        public Nullable<System.DateTime> FECHA_MODIF { get; set; }
        public short VISIBLE { get; set; }
    
        public virtual ICollection<PL_INCIDENCIA_BITACORA> PL_INCIDENCIA_BITACORA { get; set; }
    }
}
