//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PROGRAMADO_ASIGNACION
    {
        public PL_PROGRAMADO_ASIGNACION()
        {
            this.PL_ASIGNACION_RESULTADO = new HashSet<PL_ASIGNACION_RESULTADO>();
        }
    
        public int ID_PL_ASIGNACION { get; set; }
        public int ID_PL_PROGRAMADO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public short ID_SECTOR { get; set; }
        public int ID_EMPLEADO { get; set; }
        public short ID_CENTRO { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<PL_ASIGNACION_RESULTADO> PL_ASIGNACION_RESULTADO { get; set; }
        public virtual PL_PROGRAMADO PL_PROGRAMADO { get; set; }
        public virtual SECTOR SECTOR { get; set; }
    }
}
