//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PROGRAMADO_BITACORA
    {
        public PL_PROGRAMADO_BITACORA()
        {
            this.PL_ASIGNACION_BITACORA = new HashSet<PL_ASIGNACION_BITACORA>();
            this.PL_ASIGNACION_RESULTADO = new HashSet<PL_ASIGNACION_RESULTADO>();
            this.PL_INCIDENCIA_BITACORA = new HashSet<PL_INCIDENCIA_BITACORA>();
        }
    
        public int ID_PL_BITACORA { get; set; }
        public int ID_PL_PROGRAMADO { get; set; }
        public System.DateTime FECHA_EJECUCION { get; set; }
    
        public virtual ICollection<PL_ASIGNACION_BITACORA> PL_ASIGNACION_BITACORA { get; set; }
        public virtual ICollection<PL_ASIGNACION_RESULTADO> PL_ASIGNACION_RESULTADO { get; set; }
        public virtual ICollection<PL_INCIDENCIA_BITACORA> PL_INCIDENCIA_BITACORA { get; set; }
        public virtual PL_PROGRAMADO PL_PROGRAMADO { get; set; }
    }
}
