//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PROGRAMADO
    {
        public PL_PROGRAMADO()
        {
            this.PL_PROGRAMADO_ASIGNACION = new HashSet<PL_PROGRAMADO_ASIGNACION>();
            this.PL_PROGRAMADO_BITACORA = new HashSet<PL_PROGRAMADO_BITACORA>();
        }
    
        public int ID_PL_PROGRAMADO { get; set; }
        public short ID_PL_CATALOGO { get; set; }
        public short ID_CENTRO { get; set; }
        public short VIGENTE { get; set; }
        public int ID_EMPLEADO_CREADO { get; set; }
        public System.DateTime FECH_CREADO { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PL_CATALOGO PL_CATALOGO { get; set; }
        public virtual ICollection<PL_PROGRAMADO_ASIGNACION> PL_PROGRAMADO_ASIGNACION { get; set; }
        public virtual ICollection<PL_PROGRAMADO_BITACORA> PL_PROGRAMADO_BITACORA { get; set; }
    }
}
