//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR
    {
        public SECTOR()
        {
            this.CELDAs = new HashSet<CELDA>();
            this.PL_ASIGNACION_RESULTADO = new HashSet<PL_ASIGNACION_RESULTADO>();
            this.PL_PROGRAMADO_ASIGNACION = new HashSet<PL_PROGRAMADO_ASIGNACION>();
        }
    
        public short ID_CENTRO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public short ID_SECTOR { get; set; }
        public string DESCR { get; set; }
        public byte[] PLANO { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<CELDA> CELDAs { get; set; }
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual ICollection<PL_ASIGNACION_RESULTADO> PL_ASIGNACION_RESULTADO { get; set; }
        public virtual ICollection<PL_PROGRAMADO_ASIGNACION> PL_PROGRAMADO_ASIGNACION { get; set; }
    }
}
