//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PERSONA
    {
        public TIPO_PERSONA()
        {
            this.PERSONAs = new HashSet<PERSONA>();
        }
    
        public short ID_TIPO_PERSONA { get; set; }
        public string DESCR { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual ICollection<PERSONA> PERSONAs { get; set; }
    }
}
