//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PROCESO_USUARIO = new HashSet<PROCESO_USUARIO>();
            this.USUARIO_MENSAJE = new HashSet<USUARIO_MENSAJE>();
            this.USUARIO_ROL = new HashSet<USUARIO_ROL>();
            this.INGRESOes = new HashSet<INGRESO>();
        }
    
        public string ID_USUARIO { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string PASSWORD { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> VENCE_PASS { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ICollection<PROCESO_USUARIO> PROCESO_USUARIO { get; set; }
        public virtual ICollection<USUARIO_MENSAJE> USUARIO_MENSAJE { get; set; }
        public virtual ICollection<USUARIO_ROL> USUARIO_ROL { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<INGRESO> INGRESOes { get; set; }
    }
}
