//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Modelos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_DIA
    {
        public VISITA_DIA()
        {
            this.HORARIO_VISITA = new HashSet<HORARIO_VISITA>();
        }
    
        public short ID_DIA { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<HORARIO_VISITA> HORARIO_VISITA { get; set; }
    }
}
