//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdministracionContexto : DbContext
    {
        public AdministracionContexto()
            : base("name=AdministracionContexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BIOMETRICO_FORMATO> BIOMETRICO_FORMATO { get; set; }
        public DbSet<BIOMETRICO_TIPO> BIOMETRICO_TIPO { get; set; }
        public DbSet<CELDA> CELDA { get; set; }
        public DbSet<CENTRO> CENTRO { get; set; }
        public DbSet<EDIFICIO> EDIFICIO { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<IMPUTADO> IMPUTADO { get; set; }
        public DbSet<IMPUTADO_BIOMETRICO> IMPUTADO_BIOMETRICO { get; set; }
        public DbSet<INCIDENCIA> INCIDENCIA { get; set; }
        public DbSet<INCIDENTE_TIPO> INCIDENTE_TIPO { get; set; }
        public DbSet<PARAMETRO> PARAMETRO { get; set; }
        public DbSet<PASELISTA_ASIGNADO> PASELISTA_ASIGNADO { get; set; }
        public DbSet<PASELISTA_CATALOGO> PASELISTA_CATALOGO { get; set; }
        public DbSet<PASELISTA_CATALOGO_ESTATUS> PASELISTA_CATALOGO_ESTATUS { get; set; }
        public DbSet<PASELISTA_PROGRAMADO> PASELISTA_PROGRAMADO { get; set; }
        public DbSet<PASELISTA_PROGRAMADO_ESTATUS> PASELISTA_PROGRAMADO_ESTATUS { get; set; }
        public DbSet<PASELISTA_RESULTADO> PASELISTA_RESULTADO { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<PERSONA_BIOMETRICO> PERSONA_BIOMETRICO { get; set; }
        public DbSet<SECTOR> SECTOR { get; set; }
        public DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
    }
}
