//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIOMETRICO_FORMATO
    {
        public BIOMETRICO_FORMATO()
        {
            this.PERSONA_BIOMETRICO = new HashSet<PERSONA_BIOMETRICO>();
        }
    
        public short ID_FORMATO { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<PERSONA_BIOMETRICO> PERSONA_BIOMETRICO { get; set; }
    }
}
