//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDIFICIO
    {
        public EDIFICIO()
        {
            this.CELDA = new HashSet<CELDA>();
            this.PASELISTA_ASIGNADO = new HashSet<PASELISTA_ASIGNADO>();
            this.SECTOR = new HashSet<SECTOR>();
        }
    
        public short ID_EDIFICIO { get; set; }
        public short ID_CENTRO { get; set; }
        public Nullable<short> ID_TIPO_EDIFICIO { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<CELDA> CELDA { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual ICollection<PASELISTA_ASIGNADO> PASELISTA_ASIGNADO { get; set; }
        public virtual ICollection<SECTOR> SECTOR { get; set; }
    }
}
