//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.PASELISTA_ASIGNADO = new HashSet<PASELISTA_ASIGNADO>();
            this.PASELISTA_PROGRAMADO = new HashSet<PASELISTA_PROGRAMADO>();
        }
    
        public int ID_EMPLEADO { get; set; }
        public Nullable<short> ID_TIPO_EMPLEADO { get; set; }
        public Nullable<short> ID_AREA_EMP { get; set; }
        public Nullable<short> ID_CENTRO { get; set; }
        public string NUMERO_EMPLEADO { get; set; }
    
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        public virtual ICollection<PASELISTA_ASIGNADO> PASELISTA_ASIGNADO { get; set; }
        public virtual ICollection<PASELISTA_PROGRAMADO> PASELISTA_PROGRAMADO { get; set; }
    }
}
