//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASELISTA_PROGRAMADO_ESTATUS
    {
        public PASELISTA_PROGRAMADO_ESTATUS()
        {
            this.PASELISTA_PROGRAMADO = new HashSet<PASELISTA_PROGRAMADO>();
        }
    
        public short ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<PASELISTA_PROGRAMADO> PASELISTA_PROGRAMADO { get; set; }
    }
}
