//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASELISTA_CATALOGO
    {
        public PASELISTA_CATALOGO()
        {
            this.PASELISTA_PROGRAMADO = new HashSet<PASELISTA_PROGRAMADO>();
        }
    
        public short ID_PASELISTA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCR { get; set; }
        public System.DateTime HORA { get; set; }
        public short ID_STATUS { get; set; }
    
        public virtual PASELISTA_CATALOGO_ESTATUS PASELISTA_CATALOGO_ESTATUS { get; set; }
        public virtual ICollection<PASELISTA_PROGRAMADO> PASELISTA_PROGRAMADO { get; set; }
    }
}
