//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASELISTA_CATALOGO_ESTATUS
    {
        public PASELISTA_CATALOGO_ESTATUS()
        {
            this.PASELISTA_CATALOGO = new HashSet<PASELISTA_CATALOGO>();
        }
    
        public short ID_ESTATUS { get; set; }
        public string STATUS { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<PASELISTA_CATALOGO> PASELISTA_CATALOGO { get; set; }
    }
}
