//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASELISTA_PROGRAMADO
    {
        public PASELISTA_PROGRAMADO()
        {
            this.PASELISTA_ASIGNADO = new HashSet<PASELISTA_ASIGNADO>();
        }
    
        public int ID { get; set; }
        public short ID_PASELISTA { get; set; }
        public short ID_CENTRO { get; set; }
        public Nullable<short> ID_ESTATUS { get; set; }
        public Nullable<System.DateTime> FECH_MODIF { get; set; }
        public Nullable<int> ID_EMPLEADO_MODIF { get; set; }
    
        public virtual CENTRO CENTRO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<PASELISTA_ASIGNADO> PASELISTA_ASIGNADO { get; set; }
        public virtual PASELISTA_CATALOGO PASELISTA_CATALOGO { get; set; }
        public virtual PASELISTA_PROGRAMADO_ESTATUS PASELISTA_PROGRAMADO_ESTATUS { get; set; }
    }
}
