//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASELISTA_ASIGNADO
    {
        public PASELISTA_ASIGNADO()
        {
            this.PASELISTA_RESULTADO = new HashSet<PASELISTA_RESULTADO>();
        }
    
        public int ID { get; set; }
        public int ID_PASELISTA_PROGRAMADO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public short ID_SECTOR { get; set; }
        public short NIVEL_EDIFICIO { get; set; }
        public int EMPLEADO_ASIGNADO { get; set; }
        public Nullable<short> POBLACION { get; set; }
        public Nullable<System.DateTime> HORA_INICIAL { get; set; }
        public Nullable<System.DateTime> HORA_FINAL { get; set; }
    
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PASELISTA_PROGRAMADO PASELISTA_PROGRAMADO { get; set; }
        public virtual SECTOR SECTOR { get; set; }
        public virtual ICollection<PASELISTA_RESULTADO> PASELISTA_RESULTADO { get; set; }
    }
}
