//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.PERSONA_BIOMETRICO = new HashSet<PERSONA_BIOMETRICO>();
        }
    
        public int ID_PERSONA { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<PERSONA_BIOMETRICO> PERSONA_BIOMETRICO { get; set; }
    }
}
