//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.Repositorio.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR
    {
        public SECTOR()
        {
            this.CELDA = new HashSet<CELDA>();
            this.PASELISTA_ASIGNADO = new HashSet<PASELISTA_ASIGNADO>();
        }
    
        public short ID_SECTOR { get; set; }
        public short ID_CENTRO { get; set; }
        public short ID_EDIFICIO { get; set; }
        public string DESCR { get; set; }
        public byte[] PLANO { get; set; }
    
        public virtual ICollection<CELDA> CELDA { get; set; }
        public virtual CENTRO CENTRO { get; set; }
        public virtual EDIFICIO EDIFICIO { get; set; }
        public virtual ICollection<PASELISTA_ASIGNADO> PASELISTA_ASIGNADO { get; set; }
    }
}
